[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_lend_borrow = "EBDbmDQEoTCRUPg39R36iEHMNJw6R2tgchcprJBD486K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
